const eventStatuses = {
    articles: {
        ARTICLE_SUCCESSFULLY_LOADED: 'ARTICLE_SUCCESSFULLY_LOADED',
        ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',
        ARTS_LIST_LOADED: "ARTS_LIST_LOADED",
        ARTICLE_ADDED: "ARTICLE_ADDED",
        AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
        ARTICLE_ADDING_FAILED: "ARTICLE_ADDING_FAILED"
    },
    auth: {
        REGISTRATION_SUCCESFULL: "REGISTRATION_SUCCESFULL",
        REGISTRATION_ERROR: "REGISTRATION_ERROR",
        REGISTRATION_FAILED: "REGISTRATION_FAILED",
        PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
        PASSWORD_INCORRECT: "PASSWORD_INCORRECT",
        PASSWORDS_NOT_MATCH: "PASSWORDS_NOT_MATCH",
        USER_LOADED: "USER_LOADED",
        LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
        AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
        LOGIN_FAILED: "LOGIN_FAILED",
        LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
        SET_AUTH_USER: "SET_AUTH_USER",
        SET_AUTHENTICATED: "SET_AUTHENTICATED",
        SET_ID_REPRESENTING_TOKEN_REFRESH_COUNTER:
            "SET_ID_REPRESENTING_TOKEN_REFRESH_COUNTER",
        SET_USERS_LIST: "SET_USERS_LIST"
    },
    knights: {
        KAM_BUILDINGS_LOADED: "KAM_BUILDINGS_LOADED",
        KAM_UNITS_LOADED: "KAM_UNITS_LOADED"
    },
    tzar: {
        TZAR_NATIONS_LOADED: "TZAR_NATIONS_LOADED",
        TZAR_UNITS_LOADED: "TZAR_UNITS_LOADED",
        TZAR_SPELLS_LOADED: "TZAR_SPELLS_LOADED",
        TZAR_TECHNOLOGIES_LOADED: "TZAR_TECHNOLOGIES_LOADED"
    }
};

export default eventStatuses;
