const eventStatuses = {
    auth: {
        REGISTRATION_SUCCESFULL: "REGISTRATION_SUCCESFULL",
        REGISTRATION_ERROR: "REGISTRATION_ERROR",
        REGISTRATION_FAILED: "REGISTRATION_FAILED",
        PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
        PASSWORD_INCORRECT: "PASSWORD_INCORRECT",
        PASSWORDS_NOT_MATCH: "PASSWORDS_NOT_MATCH",
        USER_LOADED: "USER_LOADED",
        LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
        AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
        LOGIN_FAILED: "LOGIN_FAILED",
        LOGOUT_SUCCESSFUL: "LOGOUT_SUCCESSFUL",
        SET_AUTH_USER: "SET_AUTH_USER",
        SET_AUTHENTICATED: "SET_AUTHENTICATED",
        SET_ID_REPRESENTING_TOKEN_REFRESH_COUNTER: "SET_ID_REPRESENTING_TOKEN_REFRESH_COUNTER",
        SET_USERS_LIST: "SET_USERS_LIST"
    },
    knights: {
        KAM_BUILDINGS_LOADED: "KAM_BUILDINGS_LOADED",
        KAM_UNITS_LOADED: "KAM_UNITS_LOADED"
    }
};

export default eventStatuses;
